version: '3'

services:
  bd:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      - MSSQL_SA_PASSWORD=MyPass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
    user: root
    restart: always

    
  web:
    build: ./uni_todo
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=bd
      - DB_NAME=master
      - DB_USER=sa
      - DB_PASS=MyPass@word
    ports:
      - "8000:8000"
    depends_on:
      - bd